import type { Metadata } from "next";
import "./globals.css";
import Layout from "./layout/page";
import Head from "next/head";
export const metadata: Metadata = {
  title: "Solverines",
  description: "Generated by Solverines",
  verification: {
    google: "QZQcIZv1tAfV3jK98QNxHG7LvMGe4-qMi1DNsBy6EZY", 
  },
  icons:{
    icon:[
      {
        // url:'/images/solverines_logo1.png',
        // href:'/images/solverines_logo1.png',
        url:'/images/favicon.png',
        href:'/images/favicon.png',
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout/>
        {children}
      </body>
    </html>
  );
}
