import styles from "./page.module.css";
import Homes from "./home/page";

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: "Solverines",
  description: "Generated by Solverines",
};

export default function Home() {
  return (
    <div className={styles.page}>
      <Homes/>
    </div>
  );
}
